name: download build

inputs:
  workflow:
    required: false
  run_id:
    required: false

runs:
  using: 'composite'
  steps:
    - name: Get Run ID
      if: inputs.run_id == ''
      uses: actions/github-script@v6
      with:
        script: |
          const owner = "martis99";
          const repo = "github-actions";

          const { data } = await github.rest.actions.listWorkflowRuns({owner, repo, workflow_id: "${{ inputs.workflow }}.yml", status: "success", per_page: 1});
          const run_id = data.workflow_runs[0].id;
          echo "::set-output name=run_id::$run_id"

    - name: Download
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs/promises');
          const owner = "martis99";
          const repo = "github-actions";

          const { data } = await github.rest.actions.listWorkflowRunArtifacts({owner, repo, run_id: "${{ inputs.run_id }}"});
          await Promise.all(data.artifacts.map(async (artifact, i) => {
            const artifact_id = artifact.id;
            const { data } = await github.rest.actions.downloadArtifact({owner, repo, artifact_id, archive_format: 'zip'});
            await fs.writeFile(`${process.env.GITHUB_WORKSPACE}/download${i}.zip`, Buffer.from(data));
            console.log(`Artifact Downloaded: ${artifact.name}`);
          }));

    - name: Unzip
      shell: bash
      run: |
          unzip -o 'download*.zip'
          rm download*.zip
          chmod +x build-linux
