name: Download build

runs:
  using: 'composite'
  steps:
    - name: Download
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const owner = "martis99"
          const repo = "github-actions"
          github.rest.actions.listWorkflowRuns({owner, repo, workflow_id: "build.yml", status: "success", per_page: 1}).then(({ data }) => {
            const run_id = data.workflow_runs[0].id;
            console.log(`Last Successful Workflow Run ID: ${runId}`);
            
            github.rest.actions.listWorkflowRunArtifacts({owner, repo, run_id}).then(({ data }) => {
              data.artifacts.forEach(async (artifact) => {
                const artifact_id = artifact.id;
                console.log(`Downloading Artifact: ${artifact.name}`);
                 
                github.rest.actions.downloadArtifact({owner, repo, artifact_id, archive_format: 'zip'}).then(({ data }) => {
                  fs.writeFile(`${process.env.GITHUB_WORKSPACE}/download${i}.zip`, Buffer.from(data));
                });
              });
            });
          }).catch((error) => {
            console.error(error);
            process.exit(1);
          });
