name: Download build

runs:
  using: 'composite'
  steps:
    - name: Get Last Successful Workflow Run ID
      shell: bash
      run: |
        repo="${{inputs.repository}}"
        workflow="${{inputs.workflow}}"
        token="${{inputs.token}}"
        response=$(curl -sS "https://api.github.com/repos/martis99/github-actions/actions/workflows/build.yml/runs?status=success&per_page=1")
        last_run_id=$(echo "$response" | jq -r '.workflow_runs[0].id')
        echo "Last Successful Workflow Run ID: $last_run_id"
        echo "::set-output name=run-id::$last_run_id"

    - name: Test
      uses: actions/github-script@v6
      with:
        script: |
          const octokit = new Octokit()

          const response = await octokit.request('GET /repos/martis99/github-actions/actions/workflows/build.yml/runs?status=success&per_page=1');
          const run_id = response.workflow_runs[0].id;
          console.log(`Last Successful Workflow Run ID 2: ${run_id}`);
