name: Download build

runs:
  using: 'composite'
  steps:
    - name: Download
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs/promises'); // use fs/promises instead of fs
          const owner = "martis99";
          const repo = "github-actions";

          (async () => {
            try {
              const { data } = await github.rest.actions.listWorkflowRuns({owner, repo, workflow_id: "build.yml", status: "success", per_page: 1});
              const run_id = data.workflow_runs[0].id;
              console.log(`Last Successful Workflow Run ID: ${run_id}`);

              const { data: artifactData } = await github.rest.actions.listWorkflowRunArtifacts({owner, repo, run_id});
              await Promise.all(artifactData.artifacts.map(async (artifact, i) => {
                const artifact_id = artifact.id;
                console.log(`Downloading Artifact: ${artifact.name}`);
                const { data } = await github.rest.actions.downloadArtifact({owner, repo, artifact_id, archive_format: 'zip'});
                await fs.writeFile(`${process.env.GITHUB_WORKSPACE}/download${i}.zip`, Buffer.from(data));
                console.log(`Artifact Downloaded: ${artifact.name}`);
              }));
            } catch (error) {
              console.error(error);
              process.exit(1);
            }
          })();

    - name: Unzip
      run: |
          unzip -o 'download*.zip'
          rm download*.zip
          chmod +x build-linux
